version: '3'
services:
  db:
    image: mariadb:latest
    ports:
      - "3306:3306"
    volumes:
      - ./bin/conf.d/my.cnf:/etc/mysql/my.cnf 
      - /localdocker/geoipmaria/datadir:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example